### ISSUE TITLE
TTL issue

### ISSUE THREAD

**Issue by abaowhy** [Redislabs-Solution-Architects/riot#30]
The ttl of the target redis is reduced by 1000 times. For example, the ttl of the key on the source instance is 1000 seconds,and the ttl on the target instance is 1 second.
![image](https://user-images.githubusercontent.com/17996343/92462620-4b442b00-f1fd-11ea-9bab-11fe4d6057cb.png)

**Comment by jruaux** [comment]
Thank you for reporting this issue. I just released v2.1.1 which should fix this issue.

**Comment by radarnex** [comment]
Hi @jruaux 

With release v2.1.1 it's working great for me. Thank you!
