### ISSUE TITLE
sync elasticach cluster to redis cluster

### ISSUE THREAD

**Issue by abaowhy** [Redislabs-Solution-Architects/riot#37]
**elasticache endpoint:** rc-factor-realtime.uyffb3.clustercfg.apne1.cache.amazonaws.com:6379 
**redis cluster nodes:**
172.26.113.91:6379
172.26.113.92:6379
172.26.113.93:6379
172.26.113.94:6379
172.26.113.95:6379
172.26.113.96:6379
**sync command:**
`./riot-redis -i -c -u redis://pre-broker-cluster.uyffb3.clustercfg.apne1.cache.amazonaws.com:6379 replicate -u redis://'W6u_FZhyKhQFwbuj'@172.26.113.91:6379  --live
`
------ or --------
`
./riot-redis -i -c -u redis://pre-broker-cluster.uyffb3.clustercfg.apne1.cache.amazonaws.com:6379 replicate -c -u redis://'W6u_FZhyKhQFwbuj'@172.26.113.97:6379  --live
`
**error code:**
![image](https://user-images.githubusercontent.com/17996343/95833957-e84f3200-0d6e-11eb-99b4-deb9dab7a193.png)

**Comment by jruaux** [comment]
Hi, I just released version 2.2.3 which should fix this issue. Thanks!
