### ISSUE TITLE
Question: what kind of commands are not supported in redis replication?

### ISSUE THREAD

**Issue by GitterRemote** [Redislabs-Solution-Architects/riot#7]
How about Lua script, RPOPLPUSH, BRPOPLPUSH?

**Comment by jruaux** [comment]
Hi, RIOT replication is currently done through DUMP and RESTORE. Could you describe what you had in mind with RPOPLPUSH?

**Comment by GitterRemote** [comment]
Thank you for your reply. It is because that I first use [redis-migrate-tool](https://github.com/vipshop/redis-migrate-tool) to do Redis replication, which doesn't support these commands. So it means that when riot used with the "listen" option, whenever a new element inserted into the list, the total list will be dumped and restored to the new Redis database, isn't it?

**Comment by jruaux** [comment]
yes that is how riot works. I'll add some details in the docs about the replication mechanism
